# Generated by Django 3.1.4 on 2021-04-01 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_trends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trends',
            new_name='Trend',
        ),
    ]
