# Generated by Django 3.1.4 on 2021-04-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210401_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trend',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='trend',
            name='status',
        ),
    ]
