# Generated by Django 3.1.4 on 2021-04-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210401_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
