# Generated by Django 3.1.4 on 2021-04-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210407_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('PR', 'Programming'), ('CC', 'Cryptocurrency'), ('BC', 'Blockchain'), ('AI', 'Artificial Intelligence'), ('IOT', 'Internet of Things'), ('ML', 'Machine Learning')], default='PR', max_length=3),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='trend',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
