# Generated by Django 3.1.4 on 2021-04-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210407_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trend',
            name='id',
        ),
        migrations.AddField(
            model_name='trend',
            name='category',
            field=models.CharField(choices=[('PR', 'Programming'), ('CC', 'Cryptocurrency'), ('BC', 'Blockchain'), ('AI', 'Artificial Intelligence'), ('IOT', 'Internet of Things'), ('ML', 'Machine Learning')], default='CC', max_length=3),
        ),
        migrations.AddField(
            model_name='trend',
            name='slug',
            field=models.SlugField(default='programming', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='trend',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
