# Generated by Django 3.1.4 on 2021-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210407_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Cryptocurrency', 'Cryptocurrency'), ('Blockchain', 'Blockchain'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Internet of Things', 'Internet of Things'), ('Machine Learning', 'Machine Learning')], default='Programming', max_length=50),
        ),
        migrations.AlterField(
            model_name='trend',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Cryptocurrency', 'Cryptocurrency'), ('Blockchain', 'Blockchain'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Internet of Things', 'Internet of Things'), ('Machine Learning', 'Machine Learning')], default='Cryptocurrency', max_length=50),
        ),
    ]
