# Generated by Django 3.1.4 on 2021-04-12 14:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210412_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
    ]
