# Generated by Django 3.1.4 on 2021-04-14 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_message_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='confirmation_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
